# Generated by Django 2.2.8 on 2020-09-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('quantity', models.IntegerField(max_length=100000)),
                ('donatorname', models.CharField(max_length=100)),
                ('donator_phno', models.IntegerField(max_length=12)),
                ('donatoremail', models.EmailField(max_length=400)),
                ('donator_address', models.TextField()),
            ],
        ),
    ]
