# Generated by Django 2.2.8 on 2020-09-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('request', models.TextField(max_length=300)),
                ('quantity_needed', models.IntegerField(max_length=100000)),
                ('reciever_name', models.CharField(max_length=100)),
                ('reciever_phno', models.IntegerField(max_length=12)),
                ('recieveremail', models.EmailField(max_length=400)),
                ('reciever_address', models.TextField()),
                ('needed_by', models.DateField()),
            ],
        ),
    ]
