# Generated by Django 2.2.8 on 2020-09-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_auto_20200926_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=True, max_length=10),
            preserve_default=False,
        ),
    ]
